### ISSUE TITLE
Scripts running fine - but audio not playing

### ISSUE THREAD

**Issue by timlangedesign** [cbh123/narrator#24]
Everything seems to be working:
Getting "📸 Say cheese! Saving frame."  and "🎙️ David says:" in the terminal in VSC.

But no audio is playing, not sure how to trouble-shoot. Any ideas? 😊

**Comment by atakane** [comment]
Your answer is here https://github.com/cbh123/narrator/issues/23#issuecomment-1816795468

**Comment by timlangedesign** [comment]
@atakane Ah, I did this - got that error too and fixed the voice ID issue. The scripts are not throwing any errors.

**Comment by choboko** [comment]
I'm having a similar issue. Both "say cheese" and "David says" appear in the terminal, with the text that the narrator should be saying, but shortly after i get this: 

`Traceback (most recent call last):
  File "/Users/user/narrator/narrator.py", line 102, in <module>
    main()`
  `File "/Users/user/narrator/narrator.py", line 93, in main
    play_audio(analysis)`
 ` File "/Users/user/narrator/narrator.py", line 28, in play_audio
    audio = generate(text, voice=os.environ.get("ELEVENLABS_VOICE_ID"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
 ` File "/Users/user/narrator/venv/lib/python3.11/site-packages/elevenlabs/simple.py", line 61, in generate
    assert isinstance(voice, Voice)
AssertionError
`
