### ISSUE TITLE
A voice for the voice_id was not found

### ISSUE THREAD

**Issue by dgilperez** [cbh123/narrator#3]
Hi! Thanks for hacking this one, it's super cool :) 

Narrator doesn't work for me, the elevenpath API always returns 

```
elevenlabs.api.error.APIError: A voice for the voice_id XXX was not found.
```

where XXX is the voiceId of my freshly created voice.

any ideas? I can't find the error in their docs

**Comment by dgilperez** [comment]
Ok, found it - docs say to set `ELEVENLABS_API_TOKEN`, but the library expects `ELEVEN_API_KEY`.

**Comment by lorelupo** [comment]
I am actually getting this error even when setting `export ELEVEN_API_KEY=<mykey>`. It looks like the problem is the `voice="ENfvYmv6CRqDodDZTieQ"` argument of the `play_audio()` function

**Comment by lorelupo** [comment]
Found the solution: you should go to elevenlabs.io/voice-library and add the voice of "Brian" to your VoiceLab. Then change line `audio = generate(text=text, voice="ENfvYmv6CRqDodDZTieQ", model="eleven_turbo_v2")` with `audio = generate(text=text, voice="ENfvYmv6CRqDodDZTieQ", model="eleven_turbo_v2")`

**Comment by mattm** [comment]
If you add Brian's voice but see this error:

```bash
ValueError: Voice 'Brian' not found.
```

It's because of #4: make sure you're setting `ELEVEN_API_KEY`, not `ELEVENLABS_API_TOKEN` like it currently says in the readme.

**Comment by mattm** [comment]
I'm on a free account. Here's what I see (and it's working):

![image](https://github.com/cbh123/narrator/assets/44436/a581b9b1-663f-4763-8140-acd169482f65)

**Comment by skorokithakis** [comment]
Brian doesn't sound like David Attenborough, though, but in the video he really does. Does anyone know the actual voice?

**Comment by julianriise** [comment]
I got Brian to work, but how do we get Attenburough?

**Comment by julianriise** [comment]
I solved it, you need to buy a subscription with Elevenlabs $5/month, and create a new voice in voice lab using the "Instant voice clone" option. Upload a mp3 file of Attenbouroughs voice from this link: [https://www.mediafire.com/file/rkzphfpyzisjrrq/david.mp3/file](url), name it something like "David", and reference "David" from your narrator.py file like so:
```python
def play_audio(text):
    audio = generate(
        text=text, 
        voice="David", 
        model="eleven_turbo_v2"
        )
```

**Comment by Chris-Brauns-II** [comment]
I used "David - Gentle, Engaging, Soothing" from the existing Voice Library, and it worked pretty well!

**Comment by ciccarone** [comment]
Ah exactly what I was looking for

Very cool, I got it working and wow what a gem of how this technology can/will be used

**Comment by Althea-Texas** [comment]
Hi! I've almost got this working, but I'm getting this error message "This request's text has 590 characters and exceeds the character limit of 2500 characters for non signed in accounts." I'm currently subscribed to the Starter Account and have tried resetting my API key multiple times. I'm sooooo close. Any ideas?

**Comment by bogy0** [comment]
I had the same issue @Althea-Texas, i am also on the Starter plan. Try to logout/login and regenerate your API key, then update your env variable `ELEVEN_API_KEY` and re-run narrator.py

**Comment by greysonn** [comment]
> I had the same issue @Althea-Texas, i am also on the Starter plan. Try to logout/login and regenerate your API key, then update your env variable `ELEVEN_API_KEY` and re-run narrator.py



> Hi! I've almost got this working, but I'm getting this error message "This request's text has 590 characters and exceeds the character limit of 2500 characters for non signed in accounts." I'm currently subscribed to the Starter Account and have tried resetting my API key multiple times. I'm sooooo close. Any ideas?



I was able to fix by importing set_api_key from eleven and calling it with
`set_api_key("mykey")`
at the top of the file

**Comment by LukeAbell** [comment]
Is the "Instant Voice Cloning" option grayed out for anyone else? Just upgraded to the starter plan.

Might be the firestore issue mentioned in the banner when logging in?

**Comment by VellalaVineethKumar** [comment]
Hi @Althea-Texas ,
can you please give an example of "export ELEVENLABS_API_KEY=<eleven-token>"?

Do you know if this is how it looks? 
" https://elevenlabs.io/voice-lab/share/d04d44725c0d27dec405f110774d9520d77074476311f13c386e1dc697eeb9db/QSMJueLrQxJFcclM3UoA "

**Comment by julianriise** [comment]
> Is the "Instant Voice Cloning" option grayed out for anyone else? Just upgraded to the starter plan.

I had the same issue. Seems like an issue with Elevenlabs, I solved it by signing up with a fresh email and subscribing to the starter plan.

**Comment by julianriise** [comment]
> Hi @Althea-Texas , can you please give an example of "export ELEVENLABS_API_KEY="?
> 
> Do you know if this is how it looks? " https://elevenlabs.io/voice-lab/share/d04d44725c0d27dec405f110774d9520d77074476311f13c386e1dc697eeb9db/QSMJueLrQxJFcclM3UoA "

You can set the API key with this command (replace with an actual API key, this is just a random string).
```terminal
export ELEVEN_API_KEY="29ab7HgdklkHHfs9902jwklsjHHklk"
```

You can also check that the API was actually set with this command:
```terminal
echo $ELEVEN_API_KEY
```

**Comment by tomcharlesosman** [comment]
> If you add Brian's voice but see this error:
> 
> ```shell
> ValueError: Voice 'Brian' not found.
> ```
> 
> It's because of #4: make sure you're setting `ELEVEN_API_KEY`, not `ELEVENLABS_API_TOKEN` like it currently says in the readme.

thanks for this!

**Comment by radurosu** [comment]
Hi - Without edits am getting the below error  - 
If I replace voice="ENfvYmv6CRqDodDZTieQ"  with voice voice="Brian"  I get 
 File "/....../.pyenv/versions/3.10.10/lib/python3.10/site-packages/elevenlabs/simple.py", line 56, in generate
    raise ValueError(f"Voice '{voice_str}' not found.")
ValueError: Voice 'Brian' not found.

Any idea as to why?
Should not the David A voice be somewhere public?

 🎙️ David says:
Ah, here we observe the Homo sapiens in its natural habitat, engaging in the timeless ritual of deep contemplation. Note the furrowed brow, the glasses perched precariously, and the lone finger poised thoughtfully upon the chin—these are the hallmarks of a mind whirring at peak efficiency. Or perhaps, it's simply trying to remember if it left the kettle on. Truly, a magnificent spectacle of human cognitive prowess. Or maybe just an itchy chin. Isn't nature enthralling?
Traceback (most recent call last):
  File "/...../dev/david/venv/narrator.py", line 101, in <module>
    main()
  File "/...../dev/david/venv/narrator.py", line 92, in main
    play_audio(analysis)
  File "/...../dev/david/venv/narrator.py", line 27, in play_audio
    audio = generate(text=text, voice="ENfvYmv6CRqDodDZTieQ", model="eleven_turbo_v2")

**Comment by lorelupo** [comment]
> Hi - Without edits am getting the below error - If I replace voice="ENfvYmv6CRqDodDZTieQ" with voice voice="Brian" I get File "/....../.pyenv/versions/3.10.10/lib/python3.10/site-packages/elevenlabs/simple.py", line 56, in generate raise ValueError(f"Voice '{voice_str}' not found.") ValueError: Voice 'Brian' not found.
> 
> Any idea as to why? Should not the David A voice be somewhere public?

From your error, it looks like you haven't replaced the voice name with Brian:

```
File "/...../dev/david/venv/narrator.py", line 27, in play_audio
audio = generate(text=text, voice="ENfvYmv6CRqDodDZTieQ", model="eleven_turbo_v2")
```

If you did and still get that error, you probably haven't navigated to [elevenlabs.io/voice-library](https://elevenlabs.io/voice-library) and added the voice of Brian (or whatever other voice you wish to use) to your VoiceLab.

**Comment by KoenVdH** [comment]
Found why I always got 'voice_id was not found'.
In the readme is written export ELEVENLABS_API_KEY=<eleven-token>
but this should be export ELEVEN_API_KEY=<eleven-token>.

**Comment by radurosu** [comment]
Thanks - got it working - 

Does anyone know what is the David Attenborough voice?

**Comment by tomcharlesosman** [comment]
You have to create your own version using Instant Voice Cloning then get
the ID.

Can't use the one that's loaded i don't think.
