### ISSUE TITLE
Pydantic Version Error?

### ISSUE THREAD

**Issue by bbress** [cbh123/narrator#46]
I get the following error when I run it, do I need to change the version of pydantic or elevenlabs for it to work?

Traceback (most recent call last):
  File "/Users/robertbress/Documents/GitHub/narrator/narrator.py", line 8, in <module>
    from elevenlabs import generate, play, set_api_key, voices
  File "/Users/robertbress/anaconda3/lib/python3.11/site-packages/elevenlabs/__init__.py", line 1, in <module>
    from .api import *  # noqa F403
    ^^^^^^^^^^^^^^^^^^
  File "/Users/robertbress/anaconda3/lib/python3.11/site-packages/elevenlabs/api/__init__.py", line 2, in <module>
    from .history import *  # noqa F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertbress/anaconda3/lib/python3.11/site-packages/elevenlabs/api/history.py", line 6, in <module>
    from pydantic import model_validator
ImportError: cannot import name 'model_validator' from 'pydantic' (/Users/robertbress/anaconda3/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)
(base) robertbress@iMac-2 narrator % python narrator.py
Traceback (most recent call last):
  File "/Users/robertbress/Documents/GitHub/narrator/narrator.py", line 8, in <module>
    from elevenlabs import generate, play, set_api_key, voices
  File "/Users/robertbress/anaconda3/lib/python3.11/site-packages/elevenlabs/__init__.py", line 1, in <module>
    from .api import *  # noqa F403
    ^^^^^^^^^^^^^^^^^^
  File "/Users/robertbress/anaconda3/lib/python3.11/site-packages/elevenlabs/api/__init__.py", line 2, in <module>
    from .history import *  # noqa F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robertbress/anaconda3/lib/python3.11/site-packages/elevenlabs/api/history.py", line 6, in <module>
    from pydantic import model_validator
ImportError: cannot import name 'model_validator' from 'pydantic' (/Users/robertbress/anaconda3/lib/python3.11/site-packages/pydantic/__init__.cpython-311-darwin.so)

**Comment by bbress** [comment]
This is resolved.  Elevenlabs needs Pydantic >=1.9.2 and <2.5.  Anaconda requires <2.0.

**Comment by Assy-cmd** [comment]
<>_
