### ISSUE TITLE
Beginner's issue

### ISSUE THREAD

**Issue by lokmannacak** [cbh123/narrator#48]
Hello,

This is my first ever "programming" experience and I am having some issues, here is what I get when I try to run narrator.py

What can I do to solve this?

👀 David is watching...
Traceback (most recent call last):
  File "/Users/ME/projectai/narrator/narrator.py", line 102, in <module>
    main()
  File "/Users/ME/projectai/narrator/narrator.py", line 88, in main
    analysis = analyze_image(base64_image, script=script)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ME/projectai/narrator/narrator.py", line 57, in analyze_image
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/narrator/lib/python3.12/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/narrator/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 556, in create
    return self._post(
           ^^^^^^^^^^^
  File "/opt/anaconda3/envs/narrator/lib/python3.12/site-packages/openai/_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/narrator/lib/python3.12/site-packages/openai/_base_client.py", line 834, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/narrator/lib/python3.12/site-packages/openai/_base_client.py", line 877, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-vision-preview` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
(narrator) ME@MacBook-Pro-de-ME narrator %

**Comment by Revod** [comment]
> The model gpt-4-vision-preview does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

do you have ChatGPT 4?

**Comment by PLILI729** [comment]
I got the same isuue, and I have ChatGPT 4, please help

**Comment by backsideofdawn** [comment]
A bit late, but if you go to [https://platform.openai.com/settings/organization/billing/overview](url), then put at least $5, it will give you access to GPT 4 vision. You do have to wait a little though before it updates you to tier 1, and not the free tier. The OpenAI platform subscription is separate from your normal ChatGPT subscription.
