### ISSUE TITLE
TypeError: str expected, not NoneType

### ISSUE THREAD

**Issue by CloudPixle** [cbh123/narrator#50]
When I run Narrate.py I get the following:

Traceback (most recent call last):
  File "/Users/ahmed/Desktop/Dev/narrate/narrator/narrator.py", line 12, in <module>
    set_api_key(os.environ.get("ELEVENLABS_API_KEY"))
  File "/Users/ahmed/Desktop/Dev/narrate/venv/lib/python3.10/site-packages/elevenlabs/simple.py", line 17, in set_api_key
    os.environ["ELEVEN_API_KEY"] = api_key
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 684, in __setitem__
    value = self.encodevalue(value)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 756, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not NoneType

**Comment by Assy-cmd** [comment]
UPD'.YAEQGBGYE3.'ATE

**Comment by Assy-cmd** [comment]
YAEQGBGYE3

**Comment by Assy-cmd** [comment]
[YAEQGBGYE3``](url)
